### ISSUE TITLE
TComponent - PHP 7.4 Weak References required for storing instances of classes for Class  Behaviors

### ISSUE THREAD

**Issue by javalizard** [pradosoft/prado#728] opened 2020-12-28 05:08 UTC
This has been a LONG time coming with the release of 7.4...  The TComponent class needs to be operating on Weak References for Class-wide behaviours when applying class behaviours to already instanced objects.

This should be easy to store weak references (rather than the objects per class) but it should only work for PHP 7.4, and be "backward compatible" where compatible.

This works without the weak references but would be better object management with weak references.  This is the perfect use case for weak references.

**Comment by belisoful** [comment] 2021-03-27 07:50
**Intention**
Turn getAutoGlobalListen to TRUE for a more generous ecosystem of code behavior and functionality.  There are branches that should have this variable turned on by default like TWebControl due to its potential usefulness. In PHP version 7.4, objects can be deleted without circular references in the global event handler (required for autoGlobalListen=true).  This memory leak is stopped before PHP 7.4 with autoGloballisten=false.

**Statement of Problem**
When getAutoGlobalListen is set to true, each TComponent is listening for a global event fxAttachClassBehavior.   Capturing this event adds a reference to the component in the static variable $_ue.  The issue is that the unlisten method is called in the __destruct so as to automate the tear down process.  The unlisten removes the reference, however the object won't destruct unless the reference is removed or not there.   catch-22, leading to a memory leak when relying on the automatic unlisten feature.

All global events, and events in general [both fx and on events, but not dy events], should be weak references.

Weak references will enables objects to be destructed and have the unlisten method called automatically.

Applications can add handlers to events in many ways, so the prior used formats must be maintained.

This adds overhead to instancing every object, but with the speed increases of PHP 7, this should be marginal in performance loss.  This can be tested.

This code change must be tested in versions of PHP before 7.4 for backward compatibility without weak references. TComponent regression is required in all PHP environments tested.

Solution:
adding the pseudo-code to attaching and detaching behaviors
    if handler is array and weak reference is available then      
             set the 0 item to the 0 item object wrapped in a WeakReference

Then in raise event, check if the 0 item object is a WeakReference and if it is, get the reference.  if null, continue.

**Comment by belisoful** [comment] 2021-03-27 22:02
The new attachEventHandler
public function attachEventHandler($name, $handler, $priority = null)
	{
		if(is_array($handler) && is_object($handler[0]) && class_exists('WeakReference') && !is_a($handler[0], 'WeakReference')) {
			echo("weak reference");
			$handler[0] = WeakReference::create($handler[0]);
		}
		$this->getEventHandlers($name)->add($handler, $priority);
	}

at line 1170:
elseif (is_a($object, 'WeakReference')) {
	$object = $object->get();
	if(!$object)
		continue;
}

I have a patch waiting. but I need to test this out more first.

**Comment by belisoful** [comment] 2021-03-28 05:53
public function detachEventHandler($name, $handler, $priority = false)
	{
		if ($this->hasEventHandler($name)) {
			try {
				if(is_array($handler) && is_object($handler[0]) && class_exists('WeakReference') && !is_a($handler[0], 'WeakReference')) {
			  		$handler[0] = WeakReference::create($handler[0]);
				}
				$this->getEventHandlers($name)->remove($handler, $priority);
				return true;
			} catch (\Exception $e) {
			}
		}
		return false;
	}

**Comment by ctrlaltca** [comment] 2021-03-28 13:26
I'm sorry, but it's quite hard to evaluate code put into a github comment.

**Comment by belisoful** [comment] 2021-03-28 18:54
I'll be posting a checkin on my branch with these updates as soon as they are tested.  I got This and #733 fixed in an update.   These were tested on 7.3.11 and 7.4.9, without and with WeakReferences, to see what happens and it works very well.   I'm installing phpunit to do the full scale testing on these and to write other unit tests to check these bugs are worked out.

**Comment by belisoful** [comment] 2021-04-04 02:48
What are your thoughts on creating a TPriorityList subclass to store event handers and only keep Week References in the 0 index when an array (e.g. [$obj, 'function']).  then on outputting return everything back in their non-weak reference state.  This additional TWeakPriorityList class would revert all the weak reference changes on TComponent sans upgraded List class.

**Comment by belisoful** [comment] 2021-04-04 04:57
The current version here implementing weak references is only a partial solution.  It has helped me think about this. I really like the TWeakCallablePriorityList.   Looking at https://www.php.net/manual/en/language.types.callable.php, type 6 is not covered in the current solution for weak references and is open to apps adding their own version of with or without Weak References.

a TWeakCallablePriorityList seems ideal.  Let me see what's up with that.

**Comment by belisoful** [comment] 2021-04-04 06:18
Patching TPriorityList to be an event handler/callable collection should be easy enough.

**Comment by ctrlaltca** [comment] 2021-04-23 08:53
Fixed in #749

**Closed by ctrlaltca** 2021-04-23 08:53 UTC
Labels: bug
