### ISSUE TITLE
index.php?wsat redirecting to protected\Pages\TWsatHome.php

### ISSUE THREAD

**Issue by sicutdeux** [pradosoft/prado#660] opened 2018-01-30 22:19 UTC
Included the declaration on Services on the application.xml like this!
`<service id="wsat" class="System.Wsat.TWsatService" Password="debug" />`

URL:
http://localhost:8000/[REDACTED]/index.php?wsat

Error: 

`Unknown component type 'TWsatHome'. This may be caused by the following parsing error in the TWsatHome class file: [Warning] include_once([c:\xampp\htdocs\[REDACTED]\protected\vendor\pradosoft\prado\framework\PradoBase.php): failed to open stream: No such file or directory (@line 393 in file c:\xampp\htdocs\[REDACTED]\protected\vendor\pradosoft\prado\framework\PradoBase.php).`

URL:
http://localhost:8000/[REDACTED]/index.php?wsat=TWsatLogin

`Unknown component type 'TWsatLogin'. This may be caused by the following parsing error in the TWsatLogin class file: [Warning] include_once(C:\xampp\htdocs\[REDACTED]\protected\Pages\TWsatLogin.php): failed to open stream: No such file or directory (@line 393 in file C:\xampp\htdocs\[REDACTED]\protected\vendor\pradosoft\prado\framework\PradoBase.php).`

Then added:

`<using namespace="System.Wsat.*"/>` to path, no changes.

**Comment by sicutdeux** [comment] 2018-01-30 22:50
Using Prado 4 BTW!

**Comment by ctrlaltca** [comment] 2018-01-31 08:01
Hi, it should be fixed by 3b2f248. Thank you for the ticket!

**Closed** 2018-01-31 08:00 UTC

**Comment by opendast** [comment] 2020-01-23 10:55
It is not working on PRADO 4.1 - php 7.2
` component type 'TWsatLogin'. This may be caused by the following parsing error in the TWsatLogin class file: [Warning] include_once(/var/www/html/[FOLDER]/protected/Pages/TWsatLogin.php): failed to open stream: No such file or directory (@line 393 in file /var/www/html/[FOLDER]/protected/vendor/pradosoft/prado/framework/PradoBase.php).`
