### ISSUE TITLE
TOutputCache

### ISSUE THREAD

**Issue by majuca** [pradosoft/prado#802] opened 2021-08-20 05:05 UTC
Hi,

TOutputCache isn't working anymore with PHP 7.4 (in my case) and Prado 4.1.1.

[Warning] count(): Parameter must be an array or an object that implements Countable (@line 1702 in file /var/www/html/vysual/vendor/vysual/prado/framework/Web/UI/TControl.php).

Prado is doing a count on serialize data:

`if (count($tmp = &$control->saveStateRecursive($needViewState))) {
   $state[$control->_id] = $tmp;
}`

To test it, just add a TOutputCache in a page.

Jean-Luc

**Comment by ctrlaltca** [comment] 2021-08-24 11:10
Hi, it looks like the problem is the same reported in https://github.com/pradosoft/prado/issues/706
That has already been fixed in master. We should probably release a 4.1.2 version containing this and other bugfixes.

**Comment by ctrlaltca** [comment] 2021-08-24 12:58
I just released prado 4.1.2 that contains the fix. Can you please try it?

**Comment by majuca** [comment] 2021-08-24 14:24
It is working well for me, thank you,

**Closed** 2021-08-24 14:36 UTC
