### ISSUE TITLE
Can'T set UrlPrefix in application.xml

### ISSUE THREAD

**Issue by jo49bimpf** [pradosoft/prado#678] opened 2018-07-25 14:44 UTC
Hello,
perhaps I'm wrong here, but I wnt to try it.
I've to set a URLPrefix because of redirecting between two apache-servers.
This is my problem:

I start at
https:\web-server.de\parado-application\index.php
it will be redirected to
https:\web-server.de\2nd-location\parado-application\index.php
This will work, but then index.php will restartet with the servieid page= and parameter login.
This looks like this:

https:\web-server.de\2nd-locationparado-application\index.php?page=login

--> the \ between 2nd-location and prado-application will be removed. I think from the redirection.

So I thought, I will set the UrlPrefix in the application.xml to UrlPrefix="\2n-location"
But It won't work.
This is, how I've done it:

  
 1.   try:

\<application id="LeuTek" mode="Debug" \>

\<module class="System.Web.TUrlMapping" EnableCustomUrl="true" UrlPrefix="/statistikxxxx/" /\>

    2. try
    <module id="request" class="THttpRequest" UrlFormat="Get" UrlManager="friendly-url"/>
    <module class="System.Web.TUrlMapping" EnableCustomUrl="true" UrlPrefix="/2nd-location/" >
    <url ServiceParameter="" parameters.login="login" />
    <module>

Thanks and best regards
Juergen

**Comment by jo49bimpf** [comment] 2018-07-25 14:47
....

**Comment by ctrlaltca** [comment] 2018-07-25 15:07
Try to remove `UrlPrefix`, Prado should be able to detect it without problems when running behind apache.
Now,dDoes it works if you browse directly the second location?
If it does, than the problem is caused by the redirection.
If it doesn't, then the problem is to be searched inside the application.
In both cases, you may want to have a look at the `.htaccess` files in both application folders, as they usually contains rewrite/redirect rules.

**Comment by jo49bimpf** [comment] 2018-07-26 08:54
I've removed the UrlPrefix and I've tried to do something with rewrite in .htaccess. But with out success.
Original the .htaccess had only one line:
deny from all 
and stayed in the folder pages. And this ist the rewriterule from Apache-No-1:

\<Location /statistik\>
  ProxyPass http://localhost:7777/
  ProxyPassReverse http://localhost:7777/
  ProxySet "http://localhost:17777/" timeout=900
 \</Location\>

If I come from 
http://localhost/statisitk/prado-apll/index.php?page=login 
it will work.

if I come from 
http://localhost/statisitk/prado-apll/index.php
it will be redirected to
http://localhost/statisitkprado-apll/index.php?page=login 
which won't work because the / between statistik  and prado-apl will be removed.
I tried to fix it in the .htaccess but wihtout succes
If I set prado-apl to lala it will berewritten but with the correct folder prado-apl it comes back with the wrong url like above.

**Comment by ctrlaltca** [comment] 2018-07-26 09:33
To be honest, I'm not sure what's going on here.
The application url, used to create urls during redirection is normally extracted from `$_SERVER['SCRIPT_NAME']`, as you can see here: https://github.com/pradosoft/prado/blob/master/framework/Web/THttpRequest.php#L520
You may want to add some debug there to see what's returned.
That value is then used here: https://github.com/pradosoft/prado/blob/master/framework/Web/TUrlManager.php#L103 to build the complete url with parameters, you may want to add some debug there, too to see what's returned.
Since you are being redirected to a login page, i suppose you are using TAuthManager, so, here's another good debug point: https://github.com/pradosoft/prado/blob/master/framework/Security/TAuthManager.php#L202
The last point is inside THttpResponse, that actually renders the redirection: https://github.com/pradosoft/prado/blob/master/framework/Web/THttpResponse.php#L415 and the following function `httpRedirect($url)`

**Comment by jo49bimpf** [comment] 2018-07-26 10:16
Hello,

thanks for your fast answers!
So I found out If I do this in my index.php, it would work:

$_SERVER['SCRIPT_NAME'] = "/".$_SERVER['SCRIPT_NAME'];

But the assets won't be loaded becaus the host was removed from the links:
https://prado-apl/themes/appl-name/style.css

is at this point also this fincition used:  function parseUrl()

--> so I think I've to override this function and don't change the $_SERVER['SCRIPT_NAME']
Correct?

**Comment by jo49bimpf** [comment] 2018-07-27 06:12
Hello,

thank you for your help!

We've changed the redirect in the first Apache, so it runs now well.
Setting a rewrite in the htacces file hadn't any succes (was to late, this will be done by the second apache and the first has made the mistake so the request doesn't get to the second apache) and changes in the application.xml hadn't also any success.

thanks an best regards
Juergen

**Comment by ctrlaltca** [comment] 2018-07-27 06:33
You are welcome. Closing the issue.

**Closed by ctrlaltca** 2018-07-27 06:33 UTC
