### ISSUE TITLE
Cannot redirect to Login Page Automically

### ISSUE THREAD

**Issue by mrizkir** [pradosoft/prado#573] opened 2016-02-29 23:24 UTC
Hello,

i have a application hosted with nginx 1.6.2 and php-fpm (5.6.17), my problem in Prado 3.3 version is 
my user cannot redirect automatically to login page. 

we just get the error code http message :

![401unauthorized](https://cloud.githubusercontent.com/assets/7402103/13412443/e0429e2a-df75-11e5-97e9-5b83b1a9e91c.png)

So my user going manually to the login page http://tndetpi.yacanet.com/index.php?page=Login

**Comment by ctrlaltca** [comment] 2016-03-01 07:58
Can we see the page code somewhere? i'm no thaumaturge

**Comment by mrizkir** [comment] 2016-03-01 23:28
here is my code, and thank you very much.

protected/pages/config.xml file : 
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
	<modules>
		<module id="otorisasi_user" class="Application.Autorisasi" />
		<module id="auth" class="TAuthManager" UserManager="otorisasi_user" LoginPage="Login" />
	</modules>
	<authorization>        			                
        <allow roles="adminskpd" />
        <allow roles="bidang" />
        <allow roles="subbidang" />        
		<deny users="*" />		
	</authorization>
	<parameters>
		<parameter id="NewUserRoles" value="adminskpd,bidang,subbidang" />
	</parameters>
</configuration>

```
Protected/Autorisasi.php file :
```
<?php
prado::using('Application.UserManager');
class Autorisasi extends TModule implements IUserManager {	
	/**
	* @return string name for a guest user	
	*/		
	public function getGuestName () {
		return 'Guest';
	}	
	/**
	* returns a user instance given the username
	* @param string username, null if it is a guest
	* @return TUser the user instance, null if the specified username is not the user database
	*
	*/
	public function getUser ($username=null) {				
		if ($username === null) {
			$user = new TUser ($this);
			$user->setIsGuest(true);
			return $user;
		}else {			
			$user = new TUser ($this);						
			$um = new UserManager();
			$um->setUser($username);												
			$datauser=$um->getDataUser();	                        
            $roles='adminskpd';     
            $user->setIsGuest (false);
			$user->setRoles($roles);						
			$user->setName ($datauser);									
			return $user;		
		}
	}
	
	/**
	* validate if the username and password is correct
	* @param string username
	* @param string password
	* @return boolean true if validation is sucessful, false otherwise
	*
	*/
	public function validateUser ($username,$password) {		
		$um = new UserManager();
		$um->setUser($username);
		$result = $um->getUser();                       
		$pass=hash('sha256', $result['salt'] . hash('sha256', $password));		        
		if (($result['userpassword']==$pass) && ($result['enabled']==true))
			return true;
		else
			return false;
	}	
	/**
	* Dua method dibawah ini tidak dipakai. Tetapi harus tetap Ada.
	*
	*/			
	public function saveUserToCookie($cookie) { }
	
	public function getUserFromCookie($cookie) { }
	
	
}
?>
```
protected/UserManager.php file : 
```
<?php
class UserManager extends TAuthManager {
	/**
	* Obj DB
	*/
	private $db;		
	/**
	* Username
	*/
	private $username;					
	/**
	* data user
	*/
	private $dataUser=array('data_user'=>array(),'hak_akses'=>array());
	
	public function __construct () {
		$this->db = $this->Application->getModule('db')->getLink();						
	}
		
	/**
	* digunakan untuk mengeset username serta mensplit username dan page	
	*/
	public function setUser ($username) {		
		$this->username=$username;						
	}    
	/**
	* get roles username	
	*/
	public function getDataUser () {				
		$username=$this->username;		
        $str = "SELECT u.userid,u.username,u.userpassword,u.salt,u.nama,u.mobile_phone,u.email,u.page,u.idunitkerja,u.idbidang,b.nama_bidang,b.jeniskirim,u.idsubbidang,sbb.nama_subbidang,b.alamatsurat AS emailbidang,sbb.alamatsurat AS emailsubbidang,b.isdeleted,uk.nama_unit,uk.domain_name,foto FROM user u LEFT JOIN unitkerja uk ON (uk.idunitkerja=u.idunitkerja) LEFT JOIN bidang b ON (b.idbidang=u.idbidang) LEFT JOIN subbidang sbb ON (sbb.idsubbidang=u.idsubbidang) WHERE username='$username' AND page!='sa' AND active=1";
        $this->db->setFieldTable (array('userid','username','userpassword','salt','nama','mobile_phone','email','page','idunitkerja','nama_unit','idbidang','nama_bidang','jeniskirim','idsubbidang','nama_subbidang','emailbidang','emailsubbidang','isdeleted','domain_name','foto'));							
        $r = $this->db->getRecord($str);        
        $dataUser['logintime']=date('Y-m-d H:m:s');
        
        $dataUser['userid']=$r[1]['userid'];	
        $dataUser['username']=$r[1]['username'];	
        $dataUser['nama']=$r[1]['nama'];	
        $dataUser['mobile_phone']=$r[1]['mobile_phone'];	
        $dataUser['email']=$r[1]['email'];	
        $dataUser['page']=$r[1]['page'];
        $dataUser['foto']=$r[1]['foto'];
        $dataUser['idunitkerja']=$r[1]['idunitkerja'];
        $dataUser['nama_unit']=$r[1]['nama_unit'];	
        $dataUser['idbidang']=$r[1]['idbidang'];
        $dataUser['nama_bidang']=$r[1]['nama_bidang'];                
        $dataUser['jeniskirim']=$r[1]['jeniskirim'];
        $dataUser['alamatsurat']=$r[1]['emailbidang'];
        $dataUser['emailbidang']=$r[1]['emailbidang'].'@'.$r[1]['domain_name'];
        $dataUser['emailsubbidang']='N.A';
        $dataUser['domain_name']=$r[1]['domain_name'];                
            
        $this->dataUser['data_user']=$dataUser;
		return $dataUser;
	}
	/**
	* digunakan untuk mendapatkan data user	
	*/
	public function getUser () {				
        $str = "SELECT u.userpassword,u.page,u.salt,uk.enabled FROM user u LEFT JOIN unitkerja uk ON (uk.idunitkerja=u.idunitkerja) WHERE username='{$this->username}' AND page != 'sa' AND active=1";
        $this->db->setFieldTable (array('userpassword','salt','page','enabled'));							
        $r = $this->db->getRecord($str);				                                        
        $result=array();
        if (isset($r[1]) ) {
            $result=$r[1];            
        }        
        return $result;
	}	
}

?>
```

Protected/pages/Login.php :
```
<?php
class Login extends MainPage { 
    public function OnPreInit ($param) {	
		parent::onPreInit ($param);	
		$this->MasterClass="Application.layouts.LoginTemplate";				        
	}
	public function onLoad($param) {		
		parent::onLoad($param);				
		if (!$this->IsPostBack&&!$this->IsCallBack) {            
		}
	}    
	public function checkUsernameAndPassword($sender,$param) {		
        $username=$param->Value;
        if ($username != '') {
            try {  
                $auth = $this->Application->getModule ('auth');	                
                $password = trim(addslashes($this->txtPassword->Text));
                if (!$auth->login ($username,$password)){			                    
                    throw new Exception ("Gagal. Silahkan masukan username dan password dengan benar.");						
                }        
            }catch (Exception $e) {		
                $message='<br /><div class="alert alert-danger">
                    <strong>Error!</strong>
                    '.$e->getMessage().'</div>';
				$sender->ErrorMessage=$message;					
				$param->IsValid=false;		
			}
        }							
		
	}    
    public function checkUsernameFormat($sender,$param) {		
        $username=$param->Value;
        if ($username != '') {
            try {  
                if (!preg_match('/^[a-z\d_]{1,20}$/i', $username)||filter_var($username,FILTER_VALIDATE_EMAIL)) {			                    
                    throw new Exception ("Gagal. Silahkan masukan username dan password dengan benar.");
                }
            }catch (Exception $e) {		
                $message='<br /><div class="alert alert-danger">
                    <strong>Error!</strong>
                    '.$e->getMessage().'</div>';
				$sender->ErrorMessage=$message;					
				$param->IsValid=false;		
			}
        }							
		
	}
    public function doLogin ($sender,$param) {
        if ($this->IsValid) {                                         
            $_SESSION['ta']=date('Y');
            $this->redirect('Home',true);
        }
    }    
}
?>
```
protected/pages/Login.page file : 
```
<%@ Title="Tata Naskah Dinas - Login" %>
<com:TContent ID="content">      
<com:TTextBox ID="txtUsername" CssClass="form-control" Attributes.placeholder="Username" Attributes.autofocus="true" />                           
<com:TRequiredFieldValidator ValidationGroup="userlogin" Display="Dynamic" ControlToValidate="txtUsername" FocusOnError="true" ErrorMessage="Isi Username" />        
<com:TTextBox ID="txtPassword" Attributes.placeholder="Password" CssClass="form-control" TextMode="Password" />                                 
<com:TRequiredFieldValidator ValidationGroup="userlogin" Display="Dynamic" ControlToValidate="txtPassword" FocusOnError="true" ErrorMessage="Isi Password" />                                    
<com:TActiveCustomButton ID="btnLogin" CssClass="" ValidationGroup="userlogin" Onclick="doLogin">                            
    <prop:Text>
         Login
    </prop:Text>
    <prop:ClientSide.OnPreDispatch> 
        $('#loading').show();
        $('#<%=$this->btnLogin->ClientId%>').disabled='disabled';						        
    </prop:ClientSide.OnPreDispatch>
    <prop:ClientSide.OnLoading>
        $('#<%=$this->btnLogin->ClientId%>').disabled='disabled';									                                    
    </prop:ClientSide.OnLoading>
    <prop:ClientSide.onComplete>                                    
        $('#loading').hide();
        $('#<%=$this->btnLogin->ClientId%>').disabled='';																								                                                                                                                
    </prop:ClientSide.OnComplete>
</com:TActiveCustomButton>
<com:TActiveCustomValidator ControlToValidate="txtUsername" Display="Dynamic" OnServerValidate="checkUsernameFormat" CssClass="has-error help-block" ValidationGroup="userlogin" />
<com:TActiveCustomValidator ControlToValidate="txtUsername" Display="Dynamic" OnServerValidate="checkUsernameAndPassword" CssClass="has-error help-block" ValidationGroup="userlogin" />            
<com:TJavascriptLogger />
</com:TContent>
```

**Comment by ctrlaltca** [comment] 2016-03-02 07:56
The first strange thing that i see is that the Login page is inside ```protected/pages/```, and the configuration for that directory forbids the access to the pages for all users except those already logged in with the roles adminskpd, bidang or subbidang.
Try adding a line to the config that permits the access to the Login page to the guest users, like this one: https://github.com/pradosoft/prado/blob/master/demos/time-tracker/protected/pages/TimeTracker/config.xml#L17

**Comment by mrizkir** [comment] 2016-03-02 23:19
The result is same when i uploaded time-tracker to my nginx+php5-fpm server. please to look, http://tndetpi.yacanet.com/time-tracker.

![time-tracker](https://cloud.githubusercontent.com/assets/7402103/13479093/3473fde4-e107-11e5-95f8-466824d2e4f5.png)

Momentary solution is : i'm create landing page and then user click a link to login page.

**Comment by ctrlaltca** [comment] 2016-03-03 12:03
> please to look, http://tndetpi.yacanet.com/time-tracker.

This is not a prado error, looks more like a nginx configuration problem.

> Momentary solution is : i'm create landing page and then user click a link to login page.

Try adding to the page something like this:
```php
	public function onLoad($param)
	{
		parent::onLoad($param);

		if(!$this->IsPostBack)
		{
			if($this->User->IsGuest)
			{
				$this->Response->redirect($this->Service->constructUrl('Pages.Login', array()));
			}
		}
	}
```

**Comment by mrizkir** [comment] 2016-03-05 11:07
You are correct, when i change to Apache2.4 as back end for nginx my apps with Prado 3.3 it's working. But as you know my apps with Prado 3.2 it's working too nginx+php-fpm.


it's very confuse...

**Comment by ctrlaltca** [comment] 2016-03-24 09:03
I've made some tests runnning webapps with prado-3.3 on nging 1.8.1 + php-fpm 5.6.19, but i've been unable to reproduce your problem.
Did you solve your problem?

**Comment by ctrlaltca** [comment] 2016-03-30 15:55
Closing. Please reopen if you need further assistance.

**Closed by ctrlaltca** 2016-03-30 15:55 UTC
