### ISSUE TITLE
Internal server error when saving ActiveRecord using THtmlArea4 component

### ISSUE THREAD

**Issue by jmartens** [pradosoft/prado#719] opened 2020-06-11 07:35 UTC
When saving a page with a THtmlArea4 component I get an internal server error:

```
ajax3.js:71 Prado\Exceptions\TInvalidOperationException with message "Component property 'Prado\Security\TUser.cn' is not defined." in ${PradoFramework}\TComponent.php(652)
```

For full console log see: [localhost-1591860575883.log](https://github.com/pradosoft/prado/files/4763280/localhost-1591860575883.log)

Page I am trying this with is the same as in #710, but changed THtmlArea to THtmlArea4.

**Comment by ctrlaltca** [comment] 2020-06-11 08:13
I'm trying to use the tescase included in #710, but I've not been able to reprodute the error.
I've changed THtmlArea to THtmlArea4 and removed the custom `<prop:Options>`, since the syntax is incompatible.
I'm not sure this is caused by THtmlArea4 itself, since it's not supposed to have any iteration with the module managing users.
Do you see any instance of `User->cn` in the code somewhere?

**Comment by ctrlaltca** [comment] 2020-07-03 13:11
Ping @jmartens, have you been able to investigate the problem?

**Comment by ctrlaltca** [comment] 2020-11-26 16:35
Closing; if you still experience the problem an need support, feel free to reopen.

**Closed by ctrlaltca** 2020-11-26 16:35 UTC
